from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from poddesc.config import AppConfig, DescriptionConfig, LinkConfig
TRAILING_EXTRA_PREFIXES = (
    "以上",
    "補足",
    "説明",
    "署名",
    "Generated by",
    "Created by",
    "ChatGPT",
    "この概要欄",
)


@dataclass(frozen=True)
class DescriptionDraft:
    episode_number: str
    title: str
    topics: list[str]


def filter_topics(topics: list[str], description: DescriptionConfig | None = None) -> list[str]:
    description = description or DescriptionConfig()
    cleaned: list[str] = []
    seen: set[str] = set()

    for topic in topics:
        normalized = " ".join(str(topic).split()).strip(" /")
        if not normalized:
            continue
        if any(marker in normalized for marker in description.exclude_topic_markers):
            continue
        if normalized in seen:
            continue
        seen.add(normalized)
        cleaned.append(normalized)

    return cleaned


def filter_culture_topics(topics: list[str]) -> list[str]:
    return filter_topics(topics)


def topics_line(topics: list[str], description: DescriptionConfig | None = None) -> str:
    description = description or DescriptionConfig()
    filtered = filter_topics(topics, description)
    return description.topic_separator.join(filtered) if filtered else "トピック未設定"


def culture_topics_line(topics: list[str]) -> str:
    return topics_line(topics)


def is_topics_line_too_long(topics: str, description: DescriptionConfig | None = None, limit: int | None = None) -> bool:
    description = description or DescriptionConfig()
    return len(topics) > (limit if limit is not None else description.topic_line_warning_length)


def is_culture_line_too_long(culture_line: str, limit: int | None = None) -> bool:
    return is_topics_line_too_long(culture_line, limit=limit)


def strip_trailing_extras(description: str) -> str:
    lines = description.splitlines()

    while lines and not lines[-1].strip():
        lines.pop()

    while lines:
        last = lines[-1].strip()
        if last in {"---", "----", "-----"} or any(last.startswith(prefix) for prefix in TRAILING_EXTRA_PREFIXES):
            lines.pop()
            while lines and not lines[-1].strip():
                lines.pop()
            continue
        break

    return "\n".join(lines).rstrip() + "\n"


def render_description(
    draft: DescriptionDraft,
    config: AppConfig | None = None,
    *,
    links: Iterable[LinkConfig] | None = None,
) -> str:
    config = config or AppConfig()
    description = config.description
    rendered_links = tuple(links) if links is not None else config.links
    episode_number = draft.episode_number.strip()
    title = draft.title.strip() or "タイトル未設定"
    header = f"{episode_number}【{title}】" if episode_number else f"【{title}】"
    rendered_topics_line = topics_line(draft.topics, description)
    links_body = "\n".join(f"{link.label}：{link.url}" for link in rendered_links)

    return strip_trailing_extras(
        f"{header}\n\n"
        f"{description.intro_heading}\n"
        f"{description.intro_text.strip()}\n\n"
        f"{description.links_heading}\n"
        f"{links_body}\n\n"
        f"{description.topics_heading}\n"
        f"{rendered_topics_line}\n"
    )
